// Generated by CoffeeScript 1.10.0
var Conversion, coffee, less, marked, pug, yaml;

coffee = require("coffee-script");

less = require("less");

yaml = require("js-yaml");

marked = require("marked");

pug = require("pug");

Conversion = (function() {
  function Conversion(opts) {
    var ref;
    this.opts = opts != null ? opts : {};
    ref = this.opts, this.input = ref.input, this.type = ref.type;
    this.output = false;
    this.convert();
  }

  Conversion.prototype.convert = function() {
    switch (this.type) {
      case "coffee_to_js":
        this.output = coffee.compile(this.input, {
          bare: true
        });
        break;
      case "less_to_css":
        less.render(this.input, {}, (function(_this) {
          return function(e, output) {
            return _this.output = output.css;
          };
        })(this));
        break;
      case "yaml_to_json":
        this.output = JSON.stringify(yaml.safeLoad(this.input));
        break;
      case "pug_to_html":
        this.output = pug.render(this.input, {
          pretty: true
        });
        break;
      case "md_to_html":
        this.output = marked(this.input);
        break;
      default:
        throw new Error("conversion type '" + this.type + "' not found");
    }
    return this.output;
  };

  return Conversion;

})();

module.exports = Conversion;
