// Generated by CoffeeScript 1.10.0
var JapaneseNumber;

module.exports = JapaneseNumber = (function() {
  JapaneseNumber.lookup = {
    0: "ゼロ",
    1: "いち",
    2: "に",
    3: "さん",
    4: "よん",
    5: "ご",
    6: "ろく",
    7: "なな",
    8: "はち",
    9: "きゅう",
    10: "じゅう",
    100: "ひゃく",
    300: "さんびゃく",
    600: "ろっぴゃく",
    800: "はっぴゃく",
    1000: "せん",
    3000: "さんぜん",
    8000: "はっせん",
    10000: "まん"
  };

  JapaneseNumber.batch = function(min, max, amount) {
    var data, i, j, num, ref;
    if (min == null) {
      min = 0;
    }
    if (max == null) {
      max = 10000;
    }
    if (amount == null) {
      amount = 100;
    }
    data = [];
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      num = new JapaneseNumber(Math.floor(Math.random() * max + min));
      data.push([num.number, num.number_japanese]);
    }
    return data;
  };

  function JapaneseNumber(number) {
    this.number = number != null ? number : 0;
    this.number_japanese = this.convert(this.number);
  }

  JapaneseNumber.prototype.convert = function(num) {
    var division, divisions, j, len, remain, str, times;
    if (num == null) {
      num = this.number;
    }
    str = "";
    if (JapaneseNumber.lookup[num]) {
      str += JapaneseNumber.lookup[num];
    } else {
      divisions = [10000, 1000, 100, 10];
      for (j = 0, len = divisions.length; j < len; j++) {
        division = divisions[j];
        if (num > division) {
          times = Math.floor(num / division);
          if (JapaneseNumber.lookup[division * times] != null) {
            str += JapaneseNumber.lookup[division * times];
          } else {
            str += this.convert(times) + JapaneseNumber.lookup[division];
          }
          remain = num % (division * times);
          if (remain > 0) {
            str += this.convert(remain);
          }
          break;
        }
      }
    }
    return str;
  };

  JapaneseNumber.prototype.int = function() {
    return this.number;
  };

  JapaneseNumber.prototype.japanese = function() {
    return this.number_japanese;
  };

  JapaneseNumber.prototype.set = function(number) {
    this.number = number;
    return this.number_japanese = this.convert();
  };

  return JapaneseNumber;

})();
