// Generated by CoffeeScript 1.10.0
var Dictionary, JapaneseNumber, Quiz, QuizBuilder;

Quiz = require("./quiz.js");

JapaneseNumber = require("./japanese_number.js");

Dictionary = require("./dictionary.js");

module.exports = QuizBuilder = (function() {
  function QuizBuilder() {}

  QuizBuilder.build = function(opts1, opts) {
    var amount, key, max, min, ref, val;
    this.opts = opts1 != null ? opts1 : {};
    if (opts == null) {
      opts = {};
    }
    if (typeof this.opts === "string") {
      key = this.opts;
      this.opts = opts;
      if (key === "japanese_numbers") {
        ref = this.opts, min = ref.min, max = ref.max, amount = ref.amount;
        this.opts.question_data = JapaneseNumber.batch(min, max, amount);
      } else if (val = Dictionary.lookup(key)) {
        this.opts = {
          question_data: val
        };
      }
    }
    return new Quiz(this.opts);
  };

  return QuizBuilder;

})();
