// Generated by CoffeeScript 1.10.0
var JapaneseNumber, Quiz, QuizBuilder, dictionary_data;

Quiz = require("./quiz.js");

JapaneseNumber = require("./japanese_number.js");

dictionary_data = require("./dictionary.js");

module.exports = QuizBuilder = (function() {
  function QuizBuilder() {}

  QuizBuilder.build = function(opts1, opts) {
    var amount, key, max, min, ref;
    this.opts = opts1 != null ? opts1 : {};
    if (opts == null) {
      opts = {};
    }
    if (typeof this.opts === "string") {
      key = this.opts;
      this.opts = opts;
      if (key === "japanese_numbers") {
        ref = this.opts, min = ref.min, max = ref.max, amount = ref.amount;
        this.opts.question_data = dictionary_data.japanese_numbers(min, max, amount);
      } else if (dictionary_data[key] != null) {
        this.opts = {
          question_data: dictionary_data[key]
        };
      }
    }
    return new Quiz(this.opts);
  };

  return QuizBuilder;

})();
