// Generated by CoffeeScript 1.10.0
var View, _, pug;

_ = require("underscore");

pug = require("pug");

module.exports = View = (function() {
  function View(name, res, data) {
    this.res = res;
    this.data = data != null ? data : {};
    this.filename = (__dirname.replace(/class/, 'views')) + "/" + name + ".pug";
  }

  View.prototype.write_head = function(status) {
    return this.res.writeHead("" + status, "Content-Type: text/plain");
  };

  View.prototype.render = function(moredata) {
    var e, error, html;
    if (moredata == null) {
      moredata = {};
    }
    this.data = _.extend(this.data, moredata);
    console.log("render", this.filename);
    this.write_head(200);
    try {
      html = pug.renderFile(this.filename, this.data);
    } catch (error) {
      e = error;
      console.log("pug render error:", JSON.stringify(e));
    }
    return this.res.end(html);
  };

  return View;

})();
